apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "emir.fullname" . }}
  labels:
    app: {{ template "emir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  asda: {{ .Values.config.asda | quote }}
