apiVersion: v1
kind: Secret
metadata:
  name: {{ template "emir.fullname" . }}
  labels:
    app: {{ template "emir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  asdasda: {{ .Values.config.asdasda | quote }}
